---
- name: collect all cli test cases
  find:
    paths: "{{ role_path }}/tests/cli"
    patterns: "{{ testcase }}.yaml"
  register: cli_test_cases

- name: collect all nxapi test cases
  find:
    paths: "{{ role_path }}/tests/nxapi"
    patterns: "{{ testcase }}.yaml"
  register: nxapi_test_cases

- name: set cli_test_items
  set_fact: cli_test_items="{{ cli_test_cases.files | map(attribute='path') | list }}"

- name: set nxapi_test_items
  set_fact: nxapi_test_items="{{ nxapi_test_cases.files | map(attribute='path') | list }}"

- name: enable nxapi
  nxos_config:
    lines:
      - feature nxapi
      - nxapi http port 80
    provider: "{{ cli }}"
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: set checkpoint configuration file
  ntc_rollback:
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    platform: cisco_nxos_nxapi
    checkpoint_file: ansible_test.cfg

- name: run cli test case
  include: "{{ item }}"
  with_items: "{{ cli_test_items }}"

- name: run nxapi test case
  include: "{{ item }}"
  with_items: "{{ nxapi_test_items }}"

- name: rollback to checkpoint configuration file
  ntc_rollback:
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    platform: cisco_nxos_nxapi
    rollback_to: ansible_test.cfg

#- name: disable nxapi
#  nxos_config:
#    lines:
#      - no feature nxapi
#    provider: "{{ cli }}"
#    host: "{{ inventory_hostname }}"
#    username: "{{ username }}"
#    password: "{{ password }}"

